apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: "simple-app:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: RELEASE
              value: "{{ .Release.Name }}, {{ .Release.Namespace }}"
            - name: CHART
              value: "{{ .Chart.Name }}, {{ .Chart.Version }}"
            - name: VALUES
              value: "{{ .Values.name }}"
